### ISSUE TITLE
equals method in InstructorConflict should have only one exit

### ISSUE THREAD

**Issue by KMPyle** [skiadas/schedule-visualizer#22]
problem 14, 17
this seems like an instance that can be ignored

**Comment by davidsnowden0072** [comment]
102 line 40 in context file the method that was causing an error was the addIfNeededThenReturn and was complaining about having multiple exits instead of one. With this case we are using a map which has a specific function that should fix this issue called putIfAbsent which takes in the key and value.

**Comment by davidsnowden0072** [comment]
I have deiced to leave addIfNeededThenReturn as is. PutIfAbsent could work with this method but will not simplifying it Therefore this instance should be ignored.
